import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Layout/Header/page";
import Footer from "@/components/Layout/Footer/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" h-full w-full bg-black ">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
